server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#md5盐值
password:
  salt: geelysdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.,
#ftp配置
ftp:
  server:
    http:
      prefix: http://image.hxy.com/img/
    ip: 127.0.0.1
    port: 21
    user: hxy
    password: 123456
    remotePath: img
web:
  upload:
    handler: /upload/**
    path: F:/upload/
alipay:
  callback:
    url: http://mi5eb4.natappfree.cc/order/alipay_callback